### ISSUE TITLE
Demo link is not working?

### ISSUE THREAD

**Issue by rahulkapoor90** [ketanv3/voice#1]
fix this.

**Comment by ketanv3** [comment]
Try this link - [http://codezest.in/projects/voice/](http://codezest.in/projects/voice/)
Single tap the microphone button to listen to one single statement.
Press and hold to keep listening.

**Comment by rahulkapoor90** [comment]
Not working in Firefox.

**Comment by ketanv3** [comment]
This only works in Chrome (because it uses Chrome's speech input API).
Try it in Chrome for Desktop, or give it a shot on your Android device.

**Comment by rahulkapoor90** [comment]
okay.
